### ISSUE TITLE
"nvim_exec2(): Vim(normal):Can't re-enter normal mode from terminal mode" spammed in terminal, followed by catastrophic memory leak and full system lockup

### ISSUE THREAD

**Issue by Hubro** [karb94/neoscroll.nvim#94] opened 2024-02-26 17:31 UTC
I'm unable to reproduce this and I don't remember exactly what I did, but I was scrolling upwards in a terminal full of text inside a [floaterm](https://github.com/voldikss/vim-floaterm) window, when suddenly my Neovim instance completely locked up.

I tried to `SIGTERM` my `nvim` instance, at which point my terminal exploded with these messages:

![image](https://github.com/karb94/neoscroll.nvim/assets/597206/303c11c9-5309-4790-a1b8-13109821b4f0)

A few seconds later my entire system locked up and I saw on my second monitor that my RAM usage was 100%.

Has to take the picture with my phone camera, so pardon the quality.

I don't even know for sure if neoscroll has anything to do with this or if it was just caught in the explosion, but I thought I should at least file this somewhere.

```
$ nvim --version
NVIM v0.10.0-dev-2295+g672556525
Build type: RelWithDebInfo
LuaJIT 2.1.1707061634
Run "nvim -V1 -v" for more info
```

**Comment by karb94** [comment] 2024-03-04 21:39
Thank you for reporting this even if you can't reproduce it. I haven't tested scrolling in a terminal window so there could be some issues with it. I'll wait to see if anyone else has a similar issue before investigating further.

**Comment by karb94** [comment] 2024-09-03 23:04
Closing since no one has reported the same issue in a while

**Closed by karb94** 2024-09-03 23:04 UTC
