### ISSUE TITLE
Error on Neovim Startup

### ISSUE THREAD

**Issue by Shrimpram** [karb94/neoscroll.nvim#15] opened 2021-04-06 16:59 UTC
### Neovim throws an error on startup with neoscroll installed.

Info about my system:

* Neovim version: 0.5.0-dev+1221-g9b2d4ff62
* Package manager: Junegunn's vim plug
* Startup: init.vim
* Running Debian via WSL if that makes a difference?

### Here is the exact error message:
```
Error detected while processing /home/shreeram/dotfiles/nvim/.config/nvim/init.vim:
line  118:
E5108: Error executing lua [string ":lua"]:1: module 'neoscroll' not found:
        no field package.preload['neoscroll']
        no file './neoscroll.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/luajit-2.1.0-beta3/neoscroll.lua'
        no file '/usr/local/share/lua/5.1/neoscroll.lua'
        no file '/usr/local/share/lua/5.1/neoscroll/init.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/neoscroll.lua'
        no file '/home/runner/work/neovim/neovim/.deps/usr/share/lua/5.1/neoscroll/init.lua'
        no file './neoscroll.so'
        no file '/usr/local/lib/lua/5.1/neoscroll.so'
        no file '/home/runner/work/neovim/neovim/.deps/usr/lib/lua/5.1/neoscroll.so'
        no file '/usr/local/lib/lua/5.1/loadall.so'
```
### With reference to the error here is line 118 of my init.vim
```
115 
116 Plug 'karb94/neoscroll.nvim'
117
118 lua require('neoscroll').setup()
119
```

One odd thing I noticed is that after startup if I go and manually source my init.vim, full functionality of neoscroll returns and there is no error, so this seems to only be an issue with startup.

If there's any other info you need please let me know, neoscroll has been by far the best smooth scroll plugin I've used so I'd love to help in any way I can =)

**Comment by karb94** [comment] 2021-04-06 18:04
Before I try to run it with vim-plug myself (I'm using packer at the moment), if `lua require('neoscroll').setup()` is before `call plug#end()` could you try placing it after `call plug#end()`?

**Comment by Shrimpram** [comment] 2021-04-06 18:24
`lua require('neoscroll').setup()` was before `call plug#end()` but moving it after still gives the error. Let me try recreating with a minimal working init.vim so you can easily replicate the error, I'm a bit busy atm, might take me a few hours.

**Comment by Shrimpram** [comment] 2021-04-06 20:55
Ok oddly enough I sourced the following MWE, and then later went back to my regular init.vim, and it seems the bug is gone. MWE init.vim:
```vim
call plug#begin('~/.config/nvim/.plugged')
Plug 'karb94/neoscroll.nvim'
call plug#end()
lua require('neoscroll').setup()
```

I'm not sure why the bug has disappeared, just that it's gone now... It could show up again later, or it could just be my init.vim being the mess that it is.

Off topic question but why use packer and lua based plugins over vim-plug and vimscript? Are there speed or configurability benefits to using a lua based plugin manager or lua based plugins?

**Comment by karb94** [comment] 2021-04-07 17:18
I still can't reproduce it with the minimal init.vim you provided :confused:. If it comes back again let's investigate further but without being able to reproduce the problem there's little I can do atm. I'll close the issue for now but comment again if you get more info about the issue and I'll reopen.

Regarding the use of packer:
I've been using vim-plug up until pretty much when I started writing this plugin. Vim-plug is great but when you transition into a full lua config package managers like packer and paq that are written in lua feel more native. So I don't use vim-plug in my lua config for the same reason I wouldn't use packer in my init.vim.

Regarding lua plugins:
Are they faster? Some are, it depends on what the plugin does. Sometimes the performance difference is hard to measure. Take this plugin for instance, Lua will surely run things faster but at the end of the day I'm just sending input events to the neovim main loop so it is in neovim's hands to scroll smoothly. For instance, if there is a lot of highlighting to do it will take longer to process the input that I send to it (that is why I introduced the "performance mode". Of course, some other scrolling plugins make this problem even worse by doing lots of things in between to scrolls so this plugin might feel smoother because it's simpler. PS: I'm also working on making it even faster :wink:.

**Closed by karb94** 2021-04-07 17:18 UTC
