### ISSUE TITLE
Fails to work after opening nvim-tree

### ISSUE THREAD

**Issue by mybigman** [karb94/neoscroll.nvim#16] opened 2021-04-07 04:14 UTC
Everything works perfectly fine until you open nvim-tree.

<img width="792" alt="image" src="https://user-images.githubusercontent.com/1289916/113809461-7ef32d80-97ab-11eb-8c5c-bc13b9a18218.png">

NVIM v0.5.0-dev+1166-g070e084a6

**Comment by karb94** [comment] 2021-04-07 16:28
The error appears to be related with setting the `guicursor`. Maybe nvim-tree changes it.

- What is your `guicursor` before and after you open nvim-tree? (run `set guicursor`)
- If you close nvim-tree can you scroll normally again?

**Comment by karb94** [comment] 2021-04-07 17:26
I've tried with the following minimal init.vim and looks to be working fine for me.
```Vim
call plug#begin('~/.config/nvim/.plugged')
Plug 'karb94/neoscroll.nvim'
Plug 'kyazdani42/nvim-tree.lua'
call plug#end()
lua require('neoscroll').setup()
```
Could you provide a minimal init.vim or init.lua that reproduces the issue?

**Comment by mybigman** [comment] 2021-04-07 22:21
HI.

Before opening
```
guicursor=a:blinkon100
```

After opening
```
guicursor=n-v-c-sm:block,i-ci-ve:ver2u,r-co-o,hor20,
```

After closing nvim-tree I can nolonger scroll with your plugin. Disabling your plugin I can scroll as per normal.

**Comment by karb94** [comment] 2021-04-08 00:55
Please provide a minimal init.vim / init.lua that reproduces the issue as I cannot reproduce it at the moment. Also the second `guicursor` that you passed is not a valid one. I'm not sure how you managed to set it (or the plugin).

**Comment by karb94** [comment] 2021-04-17 18:16
Closing until further information is provided

**Closed by karb94** 2021-04-17 18:16 UTC
Labels: cannot reproduce
