### ISSUE TITLE
When scroll to the bottom or to the top, cursor is not being moved

### ISSUE THREAD

**Issue by lucastrvsn** [karb94/neoscroll.nvim#2] opened 2021-03-31 17:28 UTC
Hello! First, thank you for this plugin. It is REALLY awesome and I love to scroll on my buffers with it. But, I noted a problem when I try to scroll to the end or top of a buffer. The scroll occours normally, but the cursor is not being move to the last line or the first line of the buffer when it hit the top or bottom of a buffer.

This video show what I'm talking about, please keep track of the cursor position when I try to scroll using <C-d> and <C-u> (the first part is not using the plugin and the second is using it):

https://user-images.githubusercontent.com/8826449/113185835-527c6600-922d-11eb-9855-b6f91685cd82.mov

**Comment by karb94** [comment] 2021-03-31 19:10
Hey thanks  for your kind words. If I understand what you are saying correctly this is the intended behaviour. When `move_cursor` is set to `true` the window and the cursor will move simultaneously. If either the window or the cursor cannot be moved further it will stop. I just pushed a fix to allow you to scroll till the end of the file but stopping when the cursorline reaches the last line of the file. Try it out and see if that suits your needs.

I will consider adding an option to allow the cursor to scroll even if the window cannot be scrolled anymore like when you scroll to the top of the file.

**Comment by karb94** [comment] 2021-03-31 19:47
Pull the lastest changes. There is a new option `g:neoscroll_cursor_scrolls_alone` that might do what you want. It is disabled by default.

**Comment by dewey92** [comment] 2021-03-31 21:48
`g:neoscroll_cursor_scrolls_alone` works great man!

One feature request tho, can it stop scrolling when reaching the end of the file but keep the cursor moving like normal <C-d>? As you can see from the screenshot below, there's a lot of empty space after the last line

![image](https://user-images.githubusercontent.com/5234842/113215480-31dafd00-927b-11eb-86e7-5233da02bbde.png)

**Comment by karb94** [comment] 2021-03-31 22:45
@dewey92 If you don't want to scroll past the end of the file make sure to set `g:neoscroll_stop_eof` to `true`. As of right now the cursor won't scroll down to the bottom even with `g:neoscroll_cursor_scrolls_alone` but I will fix this in the next couple of days and that will probably become the default behaviour so that people that expect the original `<C-u>`/`<C-d>` behaviour are not disappointed with the default mappings.

**Comment by dewey92** [comment] 2021-03-31 22:50
Yeah I had tried `g:neoscroll_stop_eof = true` before but as you said, the cursor won't move when reaching eol.

Regardless, great work! I finally replaced vim-smoothie with your plugin: your default configuration seems just right to my liking 👍🏻

**Comment by lucastrvsn** [comment] 2021-04-01 13:03
Hey @karb94 thanks for you reply! I'm using the new options and everything is working great! Thank you for this! 🎉

**Comment by karb94** [comment] 2021-04-02 15:12
I just pushed a new version which addresses the issues with `g:neoscroll_stop_eof`. The defaults should now make `<C-u>`/`<C-d>` scroll in the same way as originals. Now you can combine all the available options and they should produce the expected behaviour. It was a big refactor so if something broke or doesn't work as you expect open a new issue.

**Closed by karb94** 2021-04-02 15:12 UTC

**Comment by dewey92** [comment] 2021-04-02 16:33
@karb94 working perfectly! Super thanks!
